language: node_js
node_js:
  - "7.10.1"
  - "8.11.4"
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d server/nodejs/node_modules || cd server/nodejs && rm -rf package-lock.json node_modules"

script:
  - "cd server/nodejs && npm install"
  - "npm run lint"
  - "npm run test"
